/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python: No such file or directory
/bin/sh: /env/bin/python: No such file or directory
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Traceback (most recent call last):
  File "weather_scraper.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Traceback (most recent call last):
  File "weather_scraper.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
90
6
writing
90
6
writing
90
6
writing
90
6
writing
90
6
writing
90
6
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
3
writing
90
3
writing
90
3
writing
90
3
writing
135
3
writing
135
3
writing
135
2
writing
135
2
writing
135
2
writing
135
2
writing
135
2
writing
135
2
writing
225
4
writing
225
4
writing
225
4
writing
225
4
writing
225
4
writing
225
4
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
270
9
writing
270
9
writing
270
9
writing
270
9
writing
270
9
writing
270
9
writing
270
11
writing
270
11
writing
270
11
writing
270
11
writing
270
11
writing
270
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
270
18
writing
270
18
writing
270
18
writing
270
18
writing
270
18
writing
270
18
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
12
writing
270
12
writing
315
12
writing
315
12
writing
315
12
writing
315
12
writing
315
13
writing
315
13
writing
315
13
writing
315
13
writing
315
13
writing
315
13
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
8
writing
0
8
writing
0
8
writing
0
8
writing
0
8
writing
0
8
writing
0
8
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
45
8
writing
45
8
writing
45
8
writing
45
8
writing
45
8
writing
45
8
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
5
writing
45
5
writing
45
5
writing
45
5
writing
45
5
writing
45
5
writing
45
6
writing
45
6
writing
45
6
writing
45
6
writing
45
6
writing
45
6
writing
90
5
writing
90
5
writing
90
5
writing
90
5
writing
90
5
writing
90
5
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
112.5
6
writing
112.5
6
writing
112.5
6
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
135
10
writing
135
10
writing
135
10
writing
135
10
writing
135
10
writing
135
10
writing
157.5
11
writing
157.5
11
writing
Traceback (most recent call last):
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x107385cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='weather.bm', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weather_scraper.py", line 11, in <module>
    page = requests.get(URL)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='weather.bm', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
157.5
11
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
180
15
writing
180
15
writing
180
15
writing
180
15
writing
180
15
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
13
writing
180
13
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
15
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
13
writing
225
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
225
16
writing
202.5
15
writing
202.5
15
writing
202.5
14
writing
225
13
writing
225
13
writing
225
13
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
19
writing
225
19
writing
225
19
writing
225
19
writing
225
19
writing
225
18
writing
225
18
writing
225
16
writing
225
16
writing
225
16
writing
247.5
18
writing
225
17
writing
225
17
writing
225
17
writing
225
17
writing
225
17
writing
225
17
writing
225
16
writing
225
16
writing
225
16
writing
225
16
2020-04-25 16:30:01.081950
writing
225
16
2020-04-25 16:40:01.790421
writing
225
16
2020-04-25 16:50:01.824665
writing
225
19
2020-04-25 17:00:02.297378
writing
225
19
2020-04-25 17:10:02.055771
writing
225
19
2020-04-25 17:20:02.296746
writing
225
19
2020-04-25 17:30:01.503677
writing
225
19
2020-04-25 17:40:01.856105
writing
225
20
2020-04-25 17:50:02.020047
writing
225
21
2020-04-25 18:00:01.184847
writing
225
21
2020-04-25 18:10:01.361160
writing
225
21
2020-04-25 18:20:01.545108
writing
225
21
2020-04-25 18:30:01.732499
writing
225
21
2020-04-25 18:40:00.914677
writing
225
21
2020-04-25 18:50:01.079662
writing
225
18
2020-04-25 19:00:02.054591
writing
247.5
17
2020-04-25 19:10:01.662878
writing
247.5
17
2020-04-25 19:20:02.347047
writing
225
17
2020-04-25 19:30:01.996593
writing
225
17
2020-04-25 19:40:01.790624
writing
225
17
2020-04-25 19:50:01.430261
writing
225
17
2020-04-25 20:00:02.315500
writing
225
17
2020-04-25 20:10:01.523901
writing
225
17
2020-04-25 20:20:01.665647
writing
225
17
2020-04-25 20:30:02.322483
writing
225
17
2020-04-25 20:40:02.144846
writing
225
17
2020-04-25 20:50:01.778011
writing
225
15
2020-04-25 21:00:00.909849
writing
225
15
2020-04-25 21:10:01.140365
writing
247.5
17
2020-04-25 21:20:01.875372
writing
247.5
17
2020-04-25 21:30:01.016086
writing
247.5
14
2020-04-25 21:40:01.326984
writing
247.5
14
2020-04-25 21:50:01.776926
writing
225
11
2020-04-25 22:00:00.973060
writing
225
11
2020-04-25 22:10:01.347642
writing
225
11
2020-04-25 22:20:01.637683
writing
225
11
2020-04-25 22:30:01.930123
writing
225
11
2020-04-25 22:40:01.687923
writing
225
11
2020-04-25 22:50:02.384387
writing
225
15
2020-04-25 23:00:02.108884
writing
225
15
2020-04-25 23:10:02.335405
writing
225
15
2020-04-25 23:20:02.113455
writing
225
11
2020-04-25 23:30:01.939403
writing
225
11
2020-04-25 23:40:01.575880
writing
247.5
14
2020-04-25 23:50:03.341673
writing
225
16
2020-04-26 00:00:02.189808
writing
225
16
2020-04-26 00:10:01.824260
writing
225
16
2020-04-26 00:20:01.703213
writing
225
16
2020-04-26 00:30:00.885946
writing
225
16
2020-04-26 00:40:01.005121
writing
225
16
2020-04-26 00:50:01.098758
writing
225
13
2020-04-26 01:00:01.305587
writing
225
13
2020-04-26 01:10:01.905416
writing
225
13
2020-04-26 01:20:01.062092
writing
225
13
2020-04-26 01:30:01.303816
writing
225
13
2020-04-26 01:40:01.518088
writing
225
13
2020-04-26 01:50:01.792904
writing
225
12
2020-04-26 02:00:01.004672
writing
225
12
2020-04-26 02:10:01.149836
writing
225
12
2020-04-26 02:20:01.324282
writing
225
12
2020-04-26 02:30:01.647337
writing
225
12
2020-04-26 02:40:01.794586
writing
225
12
2020-04-26 02:50:01.024452
writing
247.5
14
2020-04-26 03:00:01.432800
writing
247.5
14
2020-04-26 03:10:02.258002
writing
247.5
14
2020-04-26 03:20:01.426780
writing
247.5
14
2020-04-26 03:30:01.842102
writing
247.5
14
2020-04-26 03:40:01.740599
writing
247.5
14
2020-04-26 03:50:02.364505
writing
247.5
12
2020-04-26 04:00:02.076890
writing
247.5
12
2020-04-26 04:10:01.930387
writing
247.5
12
2020-04-26 04:20:01.711497
writing
247.5
12
2020-04-26 04:30:02.464867
writing
247.5
12
2020-04-26 04:40:01.847540
writing
247.5
12
2020-04-26 04:50:01.571890
writing
270
11
2020-04-26 05:00:02.527792
writing
270
11
2020-04-26 05:10:02.375188
writing
270
11
2020-04-26 05:20:01.553605
writing
270
11
2020-04-26 05:30:01.929262
writing
247.5
14
2020-04-26 05:40:01.041326
writing
247.5
14
2020-04-26 05:50:01.208403
writing
270
9
2020-04-26 06:00:01.342925
writing
270
9
2020-04-26 06:10:01.511375
writing
270
9
2020-04-26 06:20:01.769718
writing
270
9
2020-04-26 06:30:01.730089
writing
270
9
2020-04-26 06:40:01.659188
writing
292.5
8
2020-04-26 06:50:02.621419
writing
270
8
2020-04-26 07:00:02.306970
writing
270
8
2020-04-26 07:10:01.490630
writing
270
8
2020-04-26 07:20:01.650687
writing
247.5
8
2020-04-26 07:30:02.225392
writing
247.5
8
2020-04-26 07:40:01.578373
writing
247.5
9
2020-04-26 07:50:01.680093
writing
247.5
9
2020-04-26 08:00:02.427639
writing
247.5
9
2020-04-26 08:10:01.814801
writing
247.5
8
2020-04-26 08:20:00.980400
writing
247.5
10
2020-04-26 08:30:01.115438
writing
247.5
10
2020-04-26 08:40:01.461672
writing
247.5
10
2020-04-26 08:50:01.717534
writing
247.5
8
2020-04-26 09:00:01.575143
writing
247.5
8
2020-04-26 09:10:02.230901
writing
247.5
8
2020-04-26 09:20:01.694730
writing
270
8
2020-04-26 09:30:01.849253
writing
270
8
2020-04-26 09:40:01.177615
writing
270
8
2020-04-26 09:50:02.138891
writing
270
6
2020-04-26 10:00:02.341841
writing
270
6
2020-04-26 10:10:02.317730
writing
270
6
2020-04-26 10:20:02.469695
writing
270
6
2020-04-26 10:30:02.310366
writing
270
6
2020-04-26 10:40:01.516707
writing
270
6
2020-04-26 10:50:01.840859
writing
247.5
8
2020-04-26 11:00:00.984245
writing
247.5
8
2020-04-26 11:10:01.385958
writing
247.5
8
2020-04-26 11:20:01.614076
writing
247.5
8
2020-04-26 11:30:01.648384
writing
